#include <boost/algorithm/string.hpp>
#include <boost/bind.hpp>
#include <boost/filesystem.hpp>
#include <boost/function.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/program_options.hpp>
#include <boost/property_tree/ini_parser.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/range/adaptor/reversed.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/thread.hpp>
#include <boost/thread/mutex.hpp>
#include <boost/thread/recursive_mutex.hpp>
//#include <cgraph.h>
#include <climits>
#include <cstdlib>
#include <deque>
#include <float.h>
#include <fstream>
#include <functional>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/message.h>
//#include <gvc.h>
#include <iomanip>
#include <iostream>
#include <limits.h>
#include <list>
#include <map>
#include <math.h>
#include <memory>
#include <mutex>
//#include <QAction>
//#include <QApplication>
//#include <QCheckBox>
//#include <QColor>
//#include <QComboBox>
//#include <QDebug>
//#include <QDoubleSpinBox>
//#include <QFrame>
//#include <QGraphicsItem>
//#include <QGraphicsScene>
//#include <QGraphicsSceneContextMenuEvent>
//#include <QGroupBox>
//#include <QGVCore.h>
//#include <QGVEdge.h>
//#include <QGVEdgePrivate.h>
//#include <QGVGraphPrivate.h>
//#include <QGVGvcPrivate.h>
//#include <qgv.h>
//#include <QGVNode.h>
//#include <QGVNodePrivate.h>
//#include <QGVScene.h>
//#include <QGVSubGraph.h>
//#include <QItemDelegate>
//#include <QLineEdit>
//#include <qmainwindow.h>
//#include <QMap>
//#include <QObject>
//#include <QPainter>
//#include <QPainterPath>
//#include <QPen>
//#include <QPoint>
//#include <QPointF>
//#include <QPolygonF>
//#include <QPushButton>
//#include <QtCore/QDate>
//#include <QtCore/QDateTime>
//#include <QtCore/QLocale>
//#include <QtCore/QMap>
//#include <QtCore/QMetaEnum>
//#include <QtCore/QModelIndex>
//#include <QtCore/QSet>
//#include <QtCore/QStringList>
//#include <QtCore/QTimer>
//#include <QtCore/QVariant>
//#include <QtGlobal>
//#include <QtGui>
//#include <QtGui/QAbstractItemView>
//#include <QtGui/QApplication>
//#include <QtGui/QCheckBox>
//#include <QtGui/QColorDialog>
//#include <QtGui/QComboBox>
//#include <QtGui/QDateTimeEdit>
//#include <QtGui/QFocusEvent>
//#include <QtGui/QFontDatabase>
//#include <QtGui/QFontDialog>
//#include <QtGui/QGridLayout>
//#include <QtGui/QGroupBox>
//#include <QtGui/QHBoxLayout>
//#include <QtGui/QHeaderView>
//#include <QtGui/QIcon>
//#include <QtGui/QItemDelegate>
//#include <QtGui/QKeyEvent>
//#include <QtGui/QLabel>
//#include <QtGui/QLineEdit>
//#include <QtGui/QMenu>
//#include <QtGui/QMouseEvent>
//#include <QtGui/QPainter>
//#include <QtGui/QPalette>
//#include <QtGui/QScrollBar>
//#include <QtGui/QSpacerItem>
//#include <QtGui/QSpinBox>
//#include <QtGui/QStyle>
//#include <QtGui/QStyleOption>
//#include <QtGui/QToolButton>
//#include <QtGui/QTreeWidget>
//#include <QtGui/QWidget>
//#include <QtTest/QtTest>
//#include <QVarLengthArray>
//#include <QWebView>
//#include <QWidget>
//#include <qwt/qwt_curve_fitter.h>
//#include <qwt/qwt_legend.h>
//#include <qwt/qwt_legend_item.h>
//#include <qwt/qwt_plot_canvas.h>
//#include <qwt/qwt_plot_curve.h>
//#include <qwt/qwt_plot_directpainter.h>
//#include <qwt/qwt_plot_grid.h>
//#include <qwt/qwt_plot.h>
//#include <qwt/qwt_plot_layout.h>
//#include <qwt/qwt_plot_magnifier.h>
//#include <qwt/qwt_plot_panner.h>
//#include <qwt/qwt_scale_widget.h>
//#include <qwt/qwt_symbol.h>
//#include <QX11Info>
#include <set>
#include <signal.h>
//#include <spnav.h>
#include <sstream>
#include <stdio.h>
#include <string>
#include <unistd.h>
#include <utility>
#include <vector>
