#Import variable
Import('*')

env.Append(CPPPATH = '#server/sensors/camera')

sources = [
           'MonoCameraSensor.cc',
           'StereoCameraSensor.cc'
          ]

#staticObjs.append(env.StaticObject(sources))
sharedObjs.append(env.SharedObject(sources))
