#Import variable
Import('env sharedObjs')

sources = [
           'MonoCameraSensor.cc',
           'StereoCameraSensor.cc'
          ]

#staticObjs.append(env.StaticObject(sources))
sharedObjs.append(env.SharedObject(sources))
