#Import variable
Import('env staticObjs sharedObjs')

sources = Split('CameraSensor.cc MonoCameraSensor.cc CameraManager.cc StereoCameraSensor.cc')

staticObjs.append(env.StaticObject(sources))
sharedObjs.append(env.SharedObject(sources))
