#Import variable
Import('env staticObjs sharedObjs')

sources = Split('Gui.cc GLWindow.cc MainMenu.cc Toolbar.cc StatusBar.cc')

staticObjs.append(env.StaticObject(sources))
sharedObjs.append(env.SharedObject(sources))
