#Import variable
Import('env staticObjs sharedObjs')

dirs = Split('fltk')

for subdir in dirs :
  SConscript('%s/SConscript' % subdir)

sources = Split('Gui.cc GuiFactory.cc')

staticObjs.append( env.StaticObject(sources) )
sharedObjs.append( env.SharedObject(sources) )
