#Import variable
Import('env staticObjs sharedObjs headers')

#sources = Split('Gui.cc GuiFactory.cc GLWindow.cc MainMenu.cc Toolbar.cc StatusBar.cc')

#env = Environment()
#conf = Configure(env)
#if conf.CheckCHeader('GL/glx.h'):
sources = Split('Gui.cc DummyGui.cc GuiFactory.cc GLWindow.cc MainMenu.cc Toolbar.cc StatusBar.cc')
#env = conf.Finish()

headers.append( 
          ['server/gui/DummyGui.hh',
           'server/gui/GLWindow.hh',
           'server/gui/GuiFactory.hh',
           'server/gui/Gui.hh',
           'server/gui/MainMenu.hh',
           'server/gui/StatusBar.hh',
           'server/gui/Toolbar.hh'
           ] )

staticObjs.append(env.StaticObject(sources))
sharedObjs.append(env.SharedObject(sources))
