.TH GAZEBO 1

.SH NAME

gazebo \- start the Gazebo robotics simulator

.SH SYNOPSIS

.B gazebo [OPTIONS] <world_file>

.SH DESCRIPTION

Run the Gazebo server and GUI.

.SH OPTIONS

.TP 5
\-\-help,\-h
Produce help message.
.TP 5
\-\-pause,\-u
Start the server in a paused state.
.TP 5
\-\-physics,\-e arg
Specify a physics engine (ode|bullet).
.TP 5
\-\-play,\-p arg
Play a log file.
.TP 5
\-\-record,\-r
Record state data to disk.
.TP 5
\-\-seed arg
Start with a given random number seed.
.TP 5
\-\-server-plugin,\-s arg
Load a plugin.

.SH AUTHOR

The Open Source Robotics Foundation
