#Import variable
Import('env sharedObjs')

dirs = Split('pioneer2')

for subdir in dirs :
  SConscript('%s/SConscript' % subdir)

#sources = Split('')

#staticObjs.append(env.StaticObject(sources))
#sharedObjs.append(env.SharedObject(sources))
