#Import variable
Import('env sharedObjs headers install_prefix')

sources = ['AudioDecoder.cc', 
           'OpenAL.cc'
           ]

headers.append( 
          ['server/audio_video/AudioDecoder.hh',
           'server/audio_video/OpenAL.hh',
           ] )

sharedObjs.append( env.SharedObject(sources) )
