#Import variable
Import('*')

env.Append(CPPPATH = '#server/audio_video')

sources = ['AudioDecoder.cc', 
           'OpenAL.cc'
           ]

headers.append( 
          ['server/audio_video/AudioDecoder.hh',
           'server/audio_video/OpenAL.hh',
           ] )

sharedObjs.append( env.SharedObject(sources) )
