
# 3rd party packages
parseConfigs=['pkg-config --cflags --libs OGRE',
              'xml2-config --cflags --libs', 
      	      'ode-config --cflags --libs',
	            'pkg-config --cflags --libs OIS',
              'fltk-config --cflags --libs --use-gl --use-images',
              'xft-config --cflags --libs',
              'pkg-config --cflags --libs libgazebo',
              'pkg-config --cflags --libs libgazeboServer']


env = Environment (
  CC = 'g++',

  CCFLAGS = Split ('-pthread -pipe  -W -Wall -O2'),

  #LIBPATH=Split('#libgazebo'),
    
  #LIBS=Split('gazebo boost_python')
)


# Parse all the pacakge configurations
for cfg in parseConfigs:
  env.ParseConfig(cfg)

env.Program('simiface','simiface.cc')
