#Import variable
Import('env staticObjs sharedObjs headers')

dirs = Split('camera ray')

for subdir in dirs :
  SConscript('%s/SConscript' % subdir)

sources = Split('Sensor.cc SensorFactory.cc')

headers.append( 
          ['server/sensors/SensorFactory.hh',
           'server/sensors/SensorStub.hh',
           'server/sensors/Sensor.hh'
           ] )

staticObjs.append( env.StaticObject(sources) )
sharedObjs.append( env.SharedObject(sources) )
