#Import variable
Import('env staticObjs sharedObjs')

dirs = Split('camera ray')

for subdir in dirs :
  SConscript('%s/SConscript' % subdir)

sources = Split('Sensor.cc SensorFactory.cc')

staticObjs.append( env.StaticObject(sources) )
sharedObjs.append( env.SharedObject(sources) )
