#Import variable
Import('env staticObjs sharedObjs')

dirs = Split('camera')

for subdir in dirs :
  SConscript('%s/SConscript' % subdir)

sources = Split('Sensor.cc')

staticObjs.append( env.StaticObject(sources) )
sharedObjs.append( env.SharedObject(sources) )
