#Import variable
Import('env staticObjs sharedObjs')

sources = Split('FLTKMainWindow.cc FLTKGui.cc MainMenu.cc Toolbar.cc')

staticObjs.append(env.StaticObject(sources))
sharedObjs.append(env.SharedObject(sources))
