#Import variable
Import('*')

env.Append(CPPPATH = '#webgazebo')

env.Append(CCFLAGS = -DINSTALL_PREFIX=\\"' + install_prefix + '\\")

# We need Gazebo's quaternion functionality
sources = ['WebGazebo.cc',
           '#server/Quatern.os',
           '#server/Vector3.os',
           '#server/Angle.os']

headers = ['WebGazebo.hh']

sharedLib = env.SharedLibrary('webgazebo', sources)
#staticLib = libEnv.StaticLibrary('webgazebo', ssources)

webgazebo = env.Program('webgazebo', 'main.cc')
client = env.Program('client', 'client.cc')

env.Install(install_prefix+'/lib', sharedLib)
#env.Install(install_prefix+'/lib', staticLib)
env.Install(install_prefix+'/bin', webgazebo)
