#pragma message("Do not include this file unless generating precompiled headers")

#include <boost/algorithm/string.hpp>
#include <boost/asio.hpp>
#include <boost/bind.hpp>
#include <boost/enable_shared_from_this.hpp>
#include <boost/function.hpp>
#include <boost/interprocess/sync/interprocess_semaphore.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/thread.hpp>
#include <boost/thread/mutex.hpp>
#include <boost/thread/thread.hpp>
#include <boost/tuple/tuple.hpp>
#include <boost/unordered/unordered_set.hpp>
#include <deque>
#include <google/protobuf/message.h>
#include <iomanip>
#include <iostream>
#include <list>
#include <map>
#include <mutex>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <tbb/blocked_range.h>
#include <tbb/parallel_for.h>
#include <tbb/task.h>
#include <utility>
#include <vector>
