opts = Options()
opts.Add('sfuser', 'The Source Forge Username', 'natepak')

stuff = 'natepak'

env = Environment(options=opts)

doxBld = Builder(action='doxygen $SOURCE')
env.Append( BUILDERS={'dox' : doxBld} )

env.dox('gazebo.dox')
