import os
Import('env install_prefix staticObjs sharedObjs')

parseConfigs = ['pkg-config --cflags --libs playerc++']

sources = ['GazeboDriver.cc',
           'GazeboClient.cc',
           'GazeboInterface.cc',
           'GazeboTime.cc',
           'SimulationInterface.cc',
           'Position2dInterface.cc',
           'Position3dInterface.cc',
           'LaserInterface.cc',
           'CameraInterface.cc',
           'FiducialInterface.cc',
           'PTZInterface.cc',
           'ActarrayInterface.cc'
           ]

# Position3dInterface.cc PowerInterface.cc SonarInterface.cc   GripperInterface.cc GpsInterface.cc ')

playerEnv = env.Copy()

for cfg in parseConfigs:
  print "Checking for ["+cfg+"]"
  try:
    playerEnv.ParseConfig(cfg)
    print "  Success"
  except OSError,e:
    print "Unable to parse config ["+cfg+"]"
    if cfg.find("player") >=0:
      print "\n================================================================"
      print "Player not found, bindings will not be built."
      print "  To install player visit(http://playerstage.sourceforge.net)"
      subdirs.remove('player')
      print "================================================================"
      Return
      #time.sleep(3)


staticPlayerObjs = playerEnv.StaticObject(sources)
sharedPlayerObjs = playerEnv.SharedObject(sources)

staticPlayerObjs.append(staticObjs);
sharedPlayerObjs.append(sharedObjs);

sharedLib = playerEnv.SharedLibrary('gazeboplugin', sharedPlayerObjs)
staticLib = playerEnv.StaticLibrary('gazeboplugin', staticPlayerObjs)

env.Install(install_prefix+'/lib', sharedLib)
env.Install(install_prefix+'/lib', staticLib)
