Import('env prefix')

sources = Split('GazeboDriver.cc GazeboClient.cc GazeboInterface.cc GazeboTime.cc SimulationInterface.cc Position2dInterface.cc Graphics3dInterface.cc LaserInterface.cc')

# Position3dInterface.cc PowerInterface.cc SonarInterface.cc PtzInterface.cc ActarrayInterface.cc FiducialInterface.cc GripperInterface.cc CameraInterface.cc TruthInterface.cc GpsInterface.cc ')

sharedLib = env.SharedLibrary('gazeboplugin',sources)

env.Install(prefix+'/lib', sharedLib)
