#Import variables
Import('env install_prefix staticObjs sharedObjs headers')

dirs = Split('physics rendering sensors controllers gui')# bindings')

for subdir in dirs:
  SConscript('%s/SConscript' % subdir)

sources = ['main.cc',
           'Global.cc',
           'Vector3.cc', 
           'Quatern.cc',
           'Pose3d.cc',
           'World.cc',
           'XMLConfig.cc',
           'Time.cc',
           'Entity.cc',
           'GazeboError.cc',
           'UpdateParams.cc',
           'GazeboMessage.cc',
           'Model.cc',
           ]

headers.append( 
          ['#/server/Global.hh',
           '#/server/Vector3.hh', 
           '#/server/Quatern.hh',
           '#/server/Pose3d.hh',
           '#/server/World.hh',
           '#/server/XMLConfig.hh',
           '#/server/Time.hh',
           '#/server/Entity.hh',
           '#/server/GazeboError.hh',
           '#/server/UpdateParams.hh',
           '#/server/GazeboMessage.hh',
           '#/server/Model.hh',
           ] )

staticObjs.append( env.StaticObject(sources) )
sharedObjs.append( env.SharedObject(sources) )
