#Import variables
Import('env install_prefix staticObjs sharedObjs headers')

dirs = Split('physics rendering sensors controllers gui')# bindings')

for subdir in dirs:
  SConscript('%s/SConscript' % subdir)

sources = ['main.cc',
           'Vector3.cc', 
           'Vector4.cc', 
           'Quatern.cc',
           'Pose3d.cc',
           'World.cc',
           'XMLConfig.cc',
           'GazeboConfig.cc',
           'Time.cc',
           'Entity.cc',
           'GazeboError.cc',
           'GazeboMessage.cc',
           'Model.cc',
           'Simulator.cc',
           'Angle.cc',
           ]

headers.append( 
          ['#/server/Entity.hh',
           '#/server/GazeboError.hh',
           '#/server/GazeboMessage.hh',
           '#/server/Global.hh',
           '#/server/Model.hh',
           '#/server/Pose3d.hh',
           '#/server/Quatern.hh',
           '#/server/Simulator.hh',
           '#/server/SingletonT.hh',
           '#/server/StaticPluginRegister.hh',
           '#/server/Time.hh',
           '#/server/Vector2.hh', 
           '#/server/Vector3.hh',
           '#/server/Vector4.hh',
           '#/server/World.hh',
           '#/server/XMLConfig.hh',
           '#/server/GazeboConfig.hh',
           '#/server/Angle.hh',
           '#/server/Param.hh'
           ] )

staticObjs.append( env.StaticObject(sources) )
sharedObjs.append( env.SharedObject(sources) )
