#Import variable
Import('env staticObjs sharedObjs')

#dirs = Split('GroundPlane LightSource ObserverCam Graphics3d')
dirs = Split('LightSource')

for subdir in dirs :
  SConscript('%s/SConscript' % subdir)

sources = Split('Model.cc ModelFactory.cc')

staticObjs.append(env.StaticObject(sources))
sharedObjs.append(env.SharedObject(sources))
