#Import variable
Import('env staticObjs sharedObjs')

dirs = Split('GroundPlane LightSource ObserverCam')

for subdir in dirs :
  SConscript('%s/SConscript' % subdir)

sources = Split('Model.cc ModelFactory.cc')

staticObjs.append(env.StaticObject(sources))
sharedObjs.append(env.SharedObject(sources))
