#!/bin/sh

set -x

USAGE="USAGE: upload_www.sh <name> <sfusername>"

if [ $# -ne 2 ]; then
  echo $USAGE
  exit
fi

SFUSER=$2
NAME=$1
echo "assuming your SourceForge username is $SFUSER..."

doxygen gazebo.dox

rm -rf $NAME
cp -r html $NAME
tar cvzf $NAME.tgz $NAME

# Copy tarball to website
scp $NAME.tgz $SFUSER@shell.sourceforge.net:/home/groups/p/pl/playerstage/htdocs/doc/

ssh $SFUSER@shell.sourceforge.net 'cd /home/groups/p/pl/playerstage/htdocs/doc/; tar xzf '$NAME'.tgz; find ./'$NAME' -type d | xargs chmod -fR 2775; find ./'$NAME' -type f | xargs chmod -fR 664; rm '$NAME'.tgz'

rm -rf $NAME
rm $NAME.tgz
