#Import variable
Import('*')

env.Append(CPPPATH = '#server/rendering')

sources = [
           'OgreMovableText.cc',
           'OgreCreator.cc',
           'OgreAdaptor.cc',
           'OgreFrameListener.cc',
           'OgreDynamicRenderable.cc',
           'OgreDynamicLines.cc',
           'OgreSimpleShape.cc',
           'OgreHUD.cc',
           'OgreVisual.cc',
           'OgreCamera.cc',
           'CameraManager.cc',
           'UserCamera.cc',
           'Image.cc',
           'Color.cc'
	        ]


headers.append( 
          ['#/server/rendering/OgreMovableText.hh',
           '#/server/rendering/OgreAdaptor.hh',
           '#/server/rendering/OgreCreator.hh',
           '#/server/rendering/OgreDynamicLines.hh',
           '#/server/rendering/OgreDynamicRenderable.hh',
           '#/server/rendering/OgreFrameListener.hh',
           '#/server/rendering/OgreHUD.hh',
           '#/server/rendering/OgreSimpleShape.hh',
           '#/server/rendering/OgreVisual.hh',
           '#/server/rendering/OgreCamera.hh',
           '#/server/rendering/CameraManager.hh',
           '#/server/rendering/UserCamera.hh',
           '#/server/rendering/Image.hh',
           '#/server/rendering/Color.hh'
           ] )

#staticObjs.append( env.StaticObject(sources) )
sharedObjs.append( env.SharedObject(sources) )
