#Import variable
Import('env staticObjs sharedObjs')

sources = Split('OgreAdaptor.cc OgreFrameListener.cc OgreDynamicRenderable.cc OgreDynamicLines.cc')

staticObjs.append( env.StaticObject(sources) )
sharedObjs.append( env.SharedObject(sources) )
