#Import variable
Import('env staticObjs sharedObjs')

dirs = Split('position2d laser camera factory gripper')

for subdir in dirs :
  SConscript('%s/SConscript' % subdir)

sources = Split('Controller.cc ControllerFactory.cc')

staticObjs.append(env.StaticObject(sources))
sharedObjs.append(env.SharedObject(sources))
