#Import variable
Import('env sharedObjs headers')

dirs = Split('position2d laser camera factory gripper actarray ptz opaque bumper imu irarray')

if env["HAVE_OPENAL"] == True:
  dirs.append("audio")

for subdir in dirs :
  SConscript('%s/SConscript' % subdir)

sources = Split('Controller.cc ControllerFactory.cc')

headers.append( 
          ['#/server/controllers/ControllerFactory.hh',
           '#/server/controllers/ControllerStub.hh',
           '#/server/controllers/Controller.hh'
           ] )

#staticObjs.append(env.StaticObject(sources))
sharedObjs.append(env.SharedObject(sources))
