.TH "GZ" "1" "June 2014" "" ""
.
.SH "NAME"
\fBgzmodel_create\fR \- Gazebo command line tool to create a model template
.
.SH "SYNPOSIS"
\fBgzmodel_create\fR \fIdirectory\fR
.
.SH DESCRIPTION
\fBgzmodel_create\fP creates a template of model.config file. The required
directory argument specifies where to create the model.config file.
