.TH GAZEBO 1

.SH NAME

gztopic \- lists information about published topics on a Gazebo master

.SH SYNOPSIS

.B gztopic [command]

.SH DESCRIPTION

Lists information about published topics on a Gazebo master

.SH COMMANDS
.TP 5
list
List all topics
.TP 5
info <topic>
Get information about a topic
.TP 5
echo <topic>
Output topic data to screen
.TP 5
view <topic>
View topic data using a QT widget
.TP 5
hz <topic>
Get publish frequency
.TP 5
bw <topic>
Get topic bandwidth
.TP 5
help
Produce help message.

.SH AUTHOR

The Open Source Robotics Foundation
