
# 3rd party packages
parseConfigs=['pkg-config --cflags --libs OGRE', 
              'pkg-config --cflags --libs CEGUI-OGRE',
              'pkg-config --cflags --libs gazebo',
              'pkg-config --cflags --libs playercore',
              'pkg-config --cflags --libs playerxdr',
              'pkg-config --cflags --libs OIS']

env = Environment (
  CC = 'g++',

  CCFLAGS = Split ('-pthread -pipe  -W -Wall -O2'),

  #LIBPATH=Split('#libgazebo'),
    
  #LIBS=Split('gazebo boost_python')
)


# Parse all the pacakge configurations
for cfg in parseConfigs:
  env.ParseConfig(cfg)

sources = Split('example1.cc')

env.Program('example1',sources)
