
# 3rd party packages
parseConfigs=['pkg-config --cflags --libs libgazebo']

env = Environment (
  CC = 'g++',

  CCFLAGS = Split ('-pthread -pipe  -W -Wall -O2'),
)


# Parse all the pacakge configurations
for cfg in parseConfigs:
  env.ParseConfig(cfg)

env.Program('laser','laser.cc')
